@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Sep 22 17:02:38 +0530 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto b5e57a80f6d3429a9a9d416c8a490fbf --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot control_unit_tb_behav xil_defaultlib.control_unit_tb -log elaborate.log"
call xelab  -wto b5e57a80f6d3429a9a9d416c8a490fbf --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot control_unit_tb_behav xil_defaultlib.control_unit_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
