# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.cache/wt [current_project]
set_property parent.project_path C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/new/control_unit.vhd
  C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/new/convolve.vhd
  C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/new/mux_for_rams.vhd
  C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/new/padding.vhd
  C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/new/uart.vhd
  C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/new/median_filter.vhd
}
read_ip -quiet C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xdc]

read_ip -quiet C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/pad_conv_ram/pad_conv_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/pad_conv_ram/pad_conv_ram_ooc.xdc]

read_ip -quiet C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/input_output_ram/input_output_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/sources_1/ip/input_output_ram/input_output_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/constrs_1/new/basys3_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/ASUS/Desktop/Sem/filter_project_with_uart/filter_project_with_uart.srcs/constrs_1/new/basys3_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top median_filter -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef median_filter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file median_filter_utilization_synth.rpt -pb median_filter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
